workflows:
  third_party:
  - prepare

  third_party_only_install:
  - prepare_fast

  build:
  - build_src

  tests:
  - build_tests
  - run_tests

  release:
  - build_src_release

tasks:
  prepare: !docker
    image: builder
    commands:
    - /source/prepare.sh

  prepare_fast: !docker
    image: builder
    commands:
    - [/source/prepare.sh, --only-install]

  build_src: !docker
    image: builder
    commands:
    - [cd, "/source"]
    - [protoc, "-I=src/", "--grpc_out=src/", "--plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin", "src/mhconfig/proto/mhconfig.proto"]
    - [protoc, "-I=src/", "--cpp_out=src/", "src/mhconfig/proto/mhconfig.proto"]
    - [cd, "build"]
    - [cp, "/source/CMakeLists.txt", .]
    - [cmake, -DCMAKE_BUILD_TYPE=Debug, ..]
    - [make, -j8, mhconfig]

  build_src_release: !docker
    image: builder
    commands:
    - [cd, "/source"]
    - [protoc, "-I=src/", "--grpc_out=src/", "--plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin", "src/mhconfig/proto/mhconfig.proto"]
    - [protoc, "-I=src/", "--cpp_out=src/", "src/mhconfig/proto/mhconfig.proto"]
    - [cd, "build"]
    - [cp, "/source/CMakeLists.txt", .]
    - [cmake, -DCMAKE_BUILD_TYPE=Release, ..]
    - [make, -j8, mhconfig]

  build_tests: !docker
    image: builder
    commands:
    - [cd, "/source"]
    - [protoc, "-I=src/", "--grpc_out=src/", "--plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin", "src/mhconfig/proto/mhconfig.proto"]
    - [protoc, "-I=src/", "--cpp_out=src/", "src/mhconfig/proto/mhconfig.proto"]
    - [cd, "build"]
    - [cp, "/source/CMakeLists.txt", .]
    - [cmake, -DCMAKE_BUILD_TYPE=Debug, ..]
    - [make, -j8, tests]

  run_tests: !docker
    image: builder
    commands:
    - [cd, "/source/build"]
    - [./tests]
