version: '2.2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  cpp-builder:
    image: cpp-builder-2:0.1
    network_mode: host
    ulimits:
      nproc: 65535
      nofile: 65535
    volumes:
    - $PWD:/source

  prometheus:
    image: prom/prometheus:v2.15.2
    ulimits:
      nproc: 65535
      nofile: 65535
    volumes:
    - ./.prometheus/:/etc/prometheus/
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    ports:
    - 9090:9090

  grafana:
    image: grafana/grafana
    user: "104"
    ulimits:
      nproc: 65535
      nofile: 65535
    depends_on:
    - prometheus
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./.grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
    - ./.grafana/config.monitoring
