global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
- job_name: 'cpp-builder'
  static_configs:
  - targets: ['172.17.0.1:1111']
- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']
