{
 "title": "mhconfig",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api_type",
    "query": "label_values(api_duration_nanoseconds, type)"
   },
   {
    "name": "scheduler_type",
    "query": "label_values(scheduler_duration_nanoseconds, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_duration_nanoseconds{type=~\"$api_type\"}",
     "legendFormat": "type: {{type}}, quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_duration_nanoseconds_count{type=~\"$api_type\"}[1m])",
     "legendFormat": "type: {{type}}"
    }
   ]
  },
  {
   "title": "Scheduler duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "scheduler_duration_nanoseconds{type=~\"$scheduler_type\"}",
     "legendFormat": "type: {{type}}, quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Scheduler count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scheduler_duration_nanoseconds_count{type=~\"$scheduler_type\"}[1m])",
     "legendFormat": "type: {{type}}"
    }
   ]
  },
  {
   "title": "Serialization duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "serialization_duration_nanoseconds",
     "legendFormat": "type: {{type}}, quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Serialization count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(serialization_duration_nanoseconds_count[1m])",
     "legendFormat": "ops"
    }
   ]
  }
 ]
}