{
 "title": "mhconfig",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "api_type",
    "query": "label_values(api_duration_nanoseconds, type)"
   },
   {
    "name": "scheduler_type",
    "query": "label_values(scheduler_duration_nanoseconds, type)"
   },
   {
    "name": "worker_type",
    "query": "label_values(worker_duration_nanoseconds, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "api_duration_nanoseconds{type=~\"$api_type\"}",
       "legendFormat": "type: {{type}}, quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "Requests count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(api_duration_nanoseconds_count{type=~\"$api_type\"}[1m])",
       "legendFormat": "type: {{type}}"
      }
     ]
    },
    {
     "title": "Scheduler duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "scheduler_duration_nanoseconds{type=~\"$scheduler_type\"}",
       "legendFormat": "type: {{type}}, quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "Scheduler count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(scheduler_duration_nanoseconds_count{type=~\"$scheduler_type\"}[1m])",
       "legendFormat": "type: {{type}}"
      }
     ]
    },
    {
     "title": "Worker duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "worker_duration_nanoseconds{type=~\"$worker_type\"}",
       "legendFormat": "type: {{type}}, quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "Worker count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(worker_duration_nanoseconds_count{type=~\"$worker_type\"}[1m])",
       "legendFormat": "type: {{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Asked configs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "asked_configs",
     "legendFormat": "{{ root_path }} : {{ override }} / {{ name }}"
    }
   ]
  },
  {
   "title": "Registered watchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registered_watchers",
     "legendFormat": "{{ root_path }} : {{ override }} / {{ name }}"
    }
   ]
  },
  {
   "title": "String pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of strings",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "string_pool_num_strings", "legendFormat": "pool: {{pool}}" }
     ]
    },
    {
     "title": "Number of chunks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "string_pool_num_chunks", "legendFormat": "pool: {{pool}}" }
     ]
    },
    {
     "title": "Reclaimed space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "string_pool_reclaimed_bytes", "legendFormat": "pool: {{pool}}" }
     ]
    },
    {
     "title": "Used space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "string_pool_used_bytes", "legendFormat": "pool: {{pool}}" }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Optimized merged config size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "optimized_merged_config_used_bytes",
       "legendFormat": "quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "Optimized merged config count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "optimized_merged_config_used_bytes_count",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}