FROM gcc:8.2
MAINTAINER Juan Manuel Fdez

### base ###
RUN apt-get update && apt-get install -y --no-install-recommends \
  cmake \
  automake \
  curl \
  g++ \
  libboost-all-dev \
  libssl-dev \
  libtool \
  make \
  pkg-config \
  libomp-dev \
  valgrind \
  rsync \
  tcpdump \
  vim \
  sudo \
  ccache \
  libgoogle-perftools-dev \
  python-pip

CMD sleep infinity
